name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # Если ваша главная ветка называется master, напишите master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18" # Версия Node.js
      - run: npm install
      - run: npm run generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .output/public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2